### ISSUE TITLE
fail to compile

### ISSUE THREAD

**Issue by Alexyo21** [zaksabeast/3ds-friends-sysmodule#1]
hi, sorry for bothering but when i try to compile  it fails with this error 
![Snapshot_2023-06-06_04-03-31](https://github.com/zaksabeast/3ds-friends-sysmodule/assets/96795244/974245f0-6884-4f3a-8804-9018973cb8f4)

i'll try downgrading the devkitarm

**Comment by zaksabeast** [comment]
I just upgraded to the latest packages available with `dkp-pacman` and didn't run into this issue, so a downgrade shouldn't be necessary.

`3dsx.specs` comes from `devkitarm-crtls`: https://github.com/devkitPro/devkitarm-crtls/blob/master/3dsx.specs

Running `dkp-pacman -Sg 3ds-dev` shows the `3ds-dev` group contains `devkitarm-crtls`.

If you haven't already, try using `dkp-pacman` to install the `3ds-dev` group.  That should install everything you need.

I'm going to close the issue since this looks more like a devkitarm environment issue than a repo issue.

**Comment by Alexyo21** [comment]
Sorry i couldn't find the issue anymore cause was closed, so here i am I'll try again then thanks a lot for your time for the answer.
